Neos:
  Fusion:
    defaultContext:
      'Breadlesscode.NodeTypes.Folder.PackageManager': 'Breadlesscode\NodeTypes\Folder\Eel\Helper\PackageManagerHelper'
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Breadlesscode.NodeTypes.Folder':
            - 'NodeTypes/*/*'
    fusion:
      autoInclude:
        Breadlesscode.NodeTypes.Folder: true
